# Generated by Django 5.2.4 on 2025-09-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_generation", models.DateField(auto_now=True)),
                ("note", models.CharField(max_length=10000)),
                ("time", models.TimeField(auto_now=True)),
            ],
        ),
    ]
