# Generated by Django 5.2.4 on 2025-09-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Notes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="user_permissions",
        ),
        migrations.AddField(
            model_name="notes",
            name="slug",
            field=models.CharField(default="", max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
