# Generated by Django 5.2.4 on 2025-09-03 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Notes", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notes",
            old_name="date_of_generation",
            new_name="date",
        ),
    ]
