# Generated by Django 5.2.5 on 2025-09-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Notes", "0002_rename_date_of_generation_notes_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="notes",
            name="username",
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
