# Generated by Django 5.2.5 on 2025-09-05 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Notes", "0004_remove_notes_username_notes_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("phone_number", models.CharField(max_length=100, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("user_bio", models.CharField(max_length=50)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
